
package principal;

import centros_custo.Painel_Centros_Custo;
import clientes.Painel_Clientes;
import compras.Painel_compra;
import configuracoes.Painel_Configuracoes;
import estoque.Painel_estoque;
import financeiro.Painel_Financeiro;
import fornecedores.Painel_Fornecedores;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import login.Frm_Login;
import mesas.Painel_Mesas;
import produtos.Painel_Produtos;
import usuarios.Class_Usuarios;
import usuarios.Painel_Usuarios;
import venda.Painel_Venda;

public class Principal extends javax.swing.JFrame {

    protected String nome_usuario;
    protected int id_usuario;
    
    public Principal() {
        initComponents();
    }
    
    public Principal(int id_usuario, String nome_usuario) {
        initComponents();
        
        this.id_usuario = id_usuario;
        this.nome_usuario = nome_usuario;
        
        verificaPrivilegios();
        
        menuItemCentrosCustoActionPerformed(null);
        menuItemVendaActionPerformed(null);
    }
    
    public void verificaPrivilegios() {
        Class_Usuarios usuarios = new Class_Usuarios();
        if (!usuarios.getTipoUsuario(nome_usuario).equals("Administrador")) {
            
            //permissões de menus
            menuConfiguracoes.setVisible(false);
            menuFinanceiro.setVisible(false);

            //permissões de itens de menus
            menuItemCadastroUsuarios.setVisible(false);
            menuRelatoriosAuditoria.setVisible(false);
            menuRelatoriosUsuarios.setVisible(false);
            menuRelatoriosVendas.setVisible(false);
            menuRelatoriosFinanceiro.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel_principal = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuConfiguracoes = new javax.swing.JMenu();
        menuItemConfiguracoesSistema = new javax.swing.JMenuItem();
        menuCadastros = new javax.swing.JMenu();
        menuItemCadastroUsuarios = new javax.swing.JMenuItem();
        menuItemCadastroProdutos = new javax.swing.JMenuItem();
        menuItemCadastroFornecedores = new javax.swing.JMenuItem();
        menuItemCadastroMesas = new javax.swing.JMenuItem();
        menuItemCadastroClientes = new javax.swing.JMenuItem();
        menuEstoque = new javax.swing.JMenu();
        menuItemCentrosEstoque = new javax.swing.JMenuItem();
        menuItemCompras = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuItemVenda = new javax.swing.JMenuItem();
        menuRelatorios = new javax.swing.JMenu();
        menuRelatoriosAuditoria = new javax.swing.JMenu();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        menuRelatoriosUsuarios = new javax.swing.JMenu();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        menuRelatoriosVendas = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        menuRelatoriosFinanceiro = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        menuFinanceiro = new javax.swing.JMenu();
        menuItemCentrosCusto = new javax.swing.JMenuItem();
        menuItemSistemaFinanceiro = new javax.swing.JMenuItem();
        menuSistema = new javax.swing.JMenu();
        menuItemTrocarUsuario = new javax.swing.JMenuItem();
        menuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("BarSystem - Sistema gerenciador de bares e restaurantes - Versão 0.1.1");
        setExtendedState(MAXIMIZED_BOTH);
        setName("Principal"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        painel_principal.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jMenuBar1.setToolTipText("");

        menuConfiguracoes.setText("Configurações");
        menuConfiguracoes.setToolTipText("Realize configurações no sistema");
        menuConfiguracoes.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        menuItemConfiguracoesSistema.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuItemConfiguracoesSistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Configurações 16px.png"))); // NOI18N
        menuItemConfiguracoesSistema.setText("Configurações do sistema");
        menuItemConfiguracoesSistema.setToolTipText("Alterar as configurações do sistema");
        menuItemConfiguracoesSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemConfiguracoesSistemaActionPerformed(evt);
            }
        });
        menuConfiguracoes.add(menuItemConfiguracoesSistema);

        jMenuBar1.add(menuConfiguracoes);

        menuCadastros.setText("Cadastros");
        menuCadastros.setToolTipText("Realize os cadastros que o sistema oferece");
        menuCadastros.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuCadastros.setName("menu_Produto"); // NOI18N

        menuItemCadastroUsuarios.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuItemCadastroUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Usuario 16px.png"))); // NOI18N
        menuItemCadastroUsuarios.setText("Usuários");
        menuItemCadastroUsuarios.setToolTipText("Cadastrar usuários");
        menuItemCadastroUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadastroUsuariosActionPerformed(evt);
            }
        });
        menuCadastros.add(menuItemCadastroUsuarios);

        menuItemCadastroProdutos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuItemCadastroProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Produtos 16px.png"))); // NOI18N
        menuItemCadastroProdutos.setText("Produtos");
        menuItemCadastroProdutos.setToolTipText("Cadastrar produtos");
        menuItemCadastroProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadastroProdutosActionPerformed(evt);
            }
        });
        menuCadastros.add(menuItemCadastroProdutos);

        menuItemCadastroFornecedores.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuItemCadastroFornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Fornecedor 16px.png"))); // NOI18N
        menuItemCadastroFornecedores.setText("Fornecedores");
        menuItemCadastroFornecedores.setToolTipText("Cadastrar fornecedores");
        menuItemCadastroFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadastroFornecedoresActionPerformed(evt);
            }
        });
        menuCadastros.add(menuItemCadastroFornecedores);

        menuItemCadastroMesas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuItemCadastroMesas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Mesa 16px.png"))); // NOI18N
        menuItemCadastroMesas.setText("Mesas");
        menuItemCadastroMesas.setToolTipText("Cadastrar mesas");
        menuItemCadastroMesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadastroMesasActionPerformed(evt);
            }
        });
        menuCadastros.add(menuItemCadastroMesas);

        menuItemCadastroClientes.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuItemCadastroClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Cliente 16px.png"))); // NOI18N
        menuItemCadastroClientes.setText("Clientes");
        menuItemCadastroClientes.setToolTipText("Cadastrar clientes");
        menuItemCadastroClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadastroClientesActionPerformed(evt);
            }
        });
        menuCadastros.add(menuItemCadastroClientes);

        jMenuBar1.add(menuCadastros);

        menuEstoque.setText("Estoque");
        menuEstoque.setToolTipText("Manipule seu estoque e faça compras");
        menuEstoque.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        menuItemCentrosEstoque.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuItemCentrosEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Centro de estoque 16px.png"))); // NOI18N
        menuItemCentrosEstoque.setText("Centros de estoque");
        menuItemCentrosEstoque.setToolTipText("Cadastrar e controlar centros de estoque");
        menuItemCentrosEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCentrosEstoqueActionPerformed(evt);
            }
        });
        menuEstoque.add(menuItemCentrosEstoque);

        menuItemCompras.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuItemCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Comprar 16px.png"))); // NOI18N
        menuItemCompras.setText("Compras");
        menuItemCompras.setToolTipText("Realizar uma compra");
        menuItemCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemComprasActionPerformed(evt);
            }
        });
        menuEstoque.add(menuItemCompras);

        jMenuBar1.add(menuEstoque);

        jMenu4.setText("Bar");
        jMenu4.setToolTipText("Faça suas vendas");
        jMenu4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        menuItemVenda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        menuItemVenda.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuItemVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Bandeja 16px.png"))); // NOI18N
        menuItemVenda.setText("Venda");
        menuItemVenda.setToolTipText("Realizar uma venda");
        menuItemVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemVendaActionPerformed(evt);
            }
        });
        jMenu4.add(menuItemVenda);

        jMenuBar1.add(jMenu4);

        menuRelatorios.setText("Relatórios");
        menuRelatorios.setToolTipText("Emita relatórios para ter o controle de seu negócio");
        menuRelatorios.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        menuRelatoriosAuditoria.setText("Auditoria");
        menuRelatoriosAuditoria.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jMenuItem18.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem18.setText("Clientes");
        menuRelatoriosAuditoria.add(jMenuItem18);

        jMenuItem19.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem19.setText("Produtos");
        menuRelatoriosAuditoria.add(jMenuItem19);

        jMenuItem20.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem20.setText("Fornecedores");
        menuRelatoriosAuditoria.add(jMenuItem20);

        jMenuItem21.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem21.setText("Estoque");
        menuRelatoriosAuditoria.add(jMenuItem21);

        jMenuItem22.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem22.setText("Vendas");
        menuRelatoriosAuditoria.add(jMenuItem22);

        jMenuItem23.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem23.setText("Financeiros");
        menuRelatoriosAuditoria.add(jMenuItem23);

        menuRelatorios.add(menuRelatoriosAuditoria);

        menuRelatoriosUsuarios.setText("Usuários");
        menuRelatoriosUsuarios.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jMenuItem24.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem24.setText("Movimentações financeiras");
        menuRelatoriosUsuarios.add(jMenuItem24);

        menuRelatorios.add(menuRelatoriosUsuarios);

        jMenu2.setText("Clientes");
        jMenu2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jMenuItem2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem2.setText("Relação de clientes");
        jMenu2.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem3.setText("Dados de um cliente específico");
        jMenu2.add(jMenuItem3);

        jMenuItem4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem4.setText("Clientes inadimplentes");
        jMenu2.add(jMenuItem4);

        menuRelatorios.add(jMenu2);

        jMenu8.setText("Fornecedores");
        jMenu8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jMenuItem5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem5.setText("Relação de fornecedores");
        jMenu8.add(jMenuItem5);

        jMenuItem11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem11.setText("Dados de um fornecedor específico");
        jMenu8.add(jMenuItem11);

        menuRelatorios.add(jMenu8);

        jMenu3.setText("Estoque");
        jMenu3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jMenuItem6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem6.setText("Quantidade em estoque");
        jMenu3.add(jMenuItem6);

        jMenuItem7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem7.setText("Produtos em falta");
        jMenu3.add(jMenuItem7);

        jMenuItem9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem9.setText("Relação de compras");
        jMenu3.add(jMenuItem9);

        jMenuItem10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem10.setText("Compras agendadas");
        jMenu3.add(jMenuItem10);

        menuRelatorios.add(jMenu3);

        menuRelatoriosVendas.setText("Vendas");
        menuRelatoriosVendas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jMenuItem8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem8.setText("Vendas no bar");
        menuRelatoriosVendas.add(jMenuItem8);

        menuRelatorios.add(menuRelatoriosVendas);

        menuRelatoriosFinanceiro.setText("Financeiro");
        menuRelatoriosFinanceiro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jMenuItem12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem12.setText("Movimentação dos caixas");
        menuRelatoriosFinanceiro.add(jMenuItem12);

        jMenuItem13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem13.setText("Movimentação das contas bancárias");
        menuRelatoriosFinanceiro.add(jMenuItem13);

        jMenuItem14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem14.setText("Balancete");
        menuRelatoriosFinanceiro.add(jMenuItem14);

        jMenuItem15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem15.setText("Demonstrativo de resultados e estatísticas");
        menuRelatoriosFinanceiro.add(jMenuItem15);

        jMenuItem16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem16.setText("Receitas");
        menuRelatoriosFinanceiro.add(jMenuItem16);

        jMenuItem17.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem17.setText("Despesas");
        menuRelatoriosFinanceiro.add(jMenuItem17);

        menuRelatorios.add(menuRelatoriosFinanceiro);

        jMenuBar1.add(menuRelatorios);

        menuFinanceiro.setText("Financeiro");
        menuFinanceiro.setToolTipText("Controle suas receitas e despesas");
        menuFinanceiro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        menuItemCentrosCusto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        menuItemCentrosCusto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuItemCentrosCusto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Caixa registradora 16px.png"))); // NOI18N
        menuItemCentrosCusto.setText("Centros de custo");
        menuItemCentrosCusto.setToolTipText("Gerenciar caixa");
        menuItemCentrosCusto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCentrosCustoActionPerformed(evt);
            }
        });
        menuFinanceiro.add(menuItemCentrosCusto);

        menuItemSistemaFinanceiro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuItemSistemaFinanceiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Símbolo de dinheiro 16px.png"))); // NOI18N
        menuItemSistemaFinanceiro.setText("Sistema financeiro");
        menuItemSistemaFinanceiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSistemaFinanceiroActionPerformed(evt);
            }
        });
        menuFinanceiro.add(menuItemSistemaFinanceiro);

        jMenuBar1.add(menuFinanceiro);

        menuSistema.setText("Sistema");
        menuSistema.setToolTipText("Troque de usuário ou saia do sistema");
        menuSistema.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        menuItemTrocarUsuario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuItemTrocarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Trocar usuário 16px.png"))); // NOI18N
        menuItemTrocarUsuario.setText("Trocar de usuário");
        menuItemTrocarUsuario.setToolTipText("Abre a tela de login para escolher um usuário");
        menuItemTrocarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemTrocarUsuarioActionPerformed(evt);
            }
        });
        menuSistema.add(menuItemTrocarUsuario);

        menuItemSair.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuItemSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Sair 16px.png"))); // NOI18N
        menuItemSair.setText("Sair");
        menuItemSair.setToolTipText("Sair do sistema");
        menuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSairActionPerformed(evt);
            }
        });
        menuSistema.add(menuItemSair);

        jMenuBar1.add(menuSistema);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel_principal, javax.swing.GroupLayout.DEFAULT_SIZE, 814, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel_principal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemConfiguracoesSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemConfiguracoesSistemaActionPerformed

        Class_Verifica_Menu_Aberto verifica = new Class_Verifica_Menu_Aberto();
        int index = verifica.verificaMenuAberto(painel_principal, "Configurações do sistema   ");
        if (index >= 0)
        {
            painel_principal.setSelectedIndex(index);
        }
        else
        {
            Painel_Configuracoes conf = new Painel_Configuracoes(painel_principal);
            painel_principal.addTab("Configurações do sistema   ", new javax.swing.ImageIcon(getClass().getResource("/imagens/Configurações 16px.png")), conf, "Configure o sistema ao seu estilo de trabalho!");
            painel_principal.setSelectedIndex(painel_principal.getTabCount()-1);
        }
        
    }//GEN-LAST:event_menuItemConfiguracoesSistemaActionPerformed

    private void menuItemCadastroProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadastroProdutosActionPerformed
        
        Class_Verifica_Menu_Aberto verifica = new Class_Verifica_Menu_Aberto();
        int index = verifica.verificaMenuAberto(painel_principal, "Produtos   ");
        if (index >= 0)
        {
            painel_principal.setSelectedIndex(index);
        }
        else
        {
            Painel_Produtos cadastraProdutos = new Painel_Produtos(painel_principal);
            painel_principal.addTab("Produtos   ", new ImageIcon(getClass().getResource("/imagens/Produtos 16px.png")), cadastraProdutos, "Cadastre seus produtos!");
            cadastraProdutos.setBounds(0, 0, 500, 500);
            cadastraProdutos.setVisible(true);
            painel_principal.setSelectedIndex(painel_principal.getTabCount()-1);
            cadastraProdutos.refreshList();
        }
        
    }//GEN-LAST:event_menuItemCadastroProdutosActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        
        Class_Fechar_Sistema exit = new Class_Fechar_Sistema();
        exit.fecharSistema();
        
    }//GEN-LAST:event_formWindowClosing

    private void menuItemCadastroFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadastroFornecedoresActionPerformed
        
        Class_Verifica_Menu_Aberto verifica = new Class_Verifica_Menu_Aberto();
        int index = verifica.verificaMenuAberto(painel_principal, "Fornecedores   ");
        if (index >= 0)
        {
            painel_principal.setSelectedIndex(index);
        }
        else
        {
            Painel_Fornecedores cadastraFornecedores = new Painel_Fornecedores(painel_principal);
            painel_principal.addTab("Fornecedores   ", new ImageIcon(getClass().getResource("/imagens/Fornecedor 16px.png")), cadastraFornecedores, "Gerencie o cadastro de seus fornecedores!");
            // select the last tab
            painel_principal.setSelectedIndex(painel_principal.getTabCount()-1);
            cadastraFornecedores.refreshList();
        }
        
    }//GEN-LAST:event_menuItemCadastroFornecedoresActionPerformed

    private void menuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSairActionPerformed
        
        Class_Fechar_Sistema exit = new Class_Fechar_Sistema();
        exit.fecharSistema();
        
    }//GEN-LAST:event_menuItemSairActionPerformed

    private void menuItemCentrosEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCentrosEstoqueActionPerformed
        
        Class_Verifica_Menu_Aberto verifica = new Class_Verifica_Menu_Aberto();
        int index = verifica.verificaMenuAberto(painel_principal, "Centros de estoque   ");
        if (index >= 0)
        {
            painel_principal.setSelectedIndex(index);
        }
        else
        {
            Painel_estoque estoque = new Painel_estoque(painel_principal);
            painel_principal.addTab("Centros de estoque   ", new ImageIcon(getClass().getResource("/imagens/Centro de estoque 16px.png")), estoque, "Gerencie seus centros de estoque e transfira produtos!");
            estoque.refreshList();
            painel_principal.setSelectedIndex(painel_principal.getTabCount()-1);
        }
        
    }//GEN-LAST:event_menuItemCentrosEstoqueActionPerformed

    private void menuItemTrocarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemTrocarUsuarioActionPerformed
        
        if (JOptionPane.showConfirmDialog(null, "Deseja realmente trocar de usuário?", "Atenção", JOptionPane.YES_NO_OPTION) == 0) 
        {
            Frm_Login login = new Frm_Login();
            login.setVisible(true);

            this.dispose();
        }
        
    }//GEN-LAST:event_menuItemTrocarUsuarioActionPerformed

    private void menuItemCadastroUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadastroUsuariosActionPerformed

        Class_Verifica_Menu_Aberto verifica = new Class_Verifica_Menu_Aberto();
        int index = verifica.verificaMenuAberto(painel_principal, "Usuários   ");
        if (index >= 0)
        {
            painel_principal.setSelectedIndex(index);
        }
        else
        {
            Painel_Usuarios usuarios = new Painel_Usuarios(painel_principal);
            painel_principal.addTab("Usuários   ", new ImageIcon(getClass().getResource("/imagens/Usuario 16px.png")), usuarios, "Gerencie o cadastro dos usuários do sistema!");
            painel_principal.setSelectedIndex(painel_principal.getTabCount()-1);
            usuarios.refreshList();
        }
        
    }//GEN-LAST:event_menuItemCadastroUsuariosActionPerformed

    private void menuItemVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemVendaActionPerformed
        
        Class_Verifica_Menu_Aberto verifica = new Class_Verifica_Menu_Aberto();
        int index = verifica.verificaMenuAberto(painel_principal, "Vendas   ");
        if (index >= 0)
        {
            painel_principal.setSelectedIndex(index);
        }
        else
        {
            Painel_Venda venda = new Painel_Venda(this, painel_principal);
            painel_principal.addTab("Vendas   ", new ImageIcon(getClass().getResource("/imagens/Bandeja 16px.png")), venda, "Gerencie mesas e venda produtos!");
            painel_principal.setSelectedIndex(painel_principal.getTabCount()-1);
        }
        
    }//GEN-LAST:event_menuItemVendaActionPerformed

    private void menuItemCentrosCustoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCentrosCustoActionPerformed
        
        Class_Verifica_Menu_Aberto verifica = new Class_Verifica_Menu_Aberto();
        int index = verifica.verificaMenuAberto(painel_principal, "Centros de custo   ");
        if (index >= 0)
        {
            painel_principal.setSelectedIndex(index);
        }
        else
        {
            Painel_Centros_Custo centros_custo = new Painel_Centros_Custo(this, painel_principal, this.id_usuario, this.nome_usuario);
            painel_principal.addTab("Centros de custo   ", new ImageIcon(getClass().getResource("/imagens/Caixa registradora 16px.png")), centros_custo, "Gerencie os seus recebimentos!");
            centros_custo.adicionaCentrosCusto();
            painel_principal.setSelectedIndex(painel_principal.getTabCount()-1);
        }
        
    }//GEN-LAST:event_menuItemCentrosCustoActionPerformed

    private void menuItemComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemComprasActionPerformed
        
        Painel_compra compra = new Painel_compra();
        compra.refreshCombo_Fornecedor();
        compra.refreshFormaPagamento();
        painel_principal.add(compra);
        compra.refreshTable();
        
    }//GEN-LAST:event_menuItemComprasActionPerformed

    private void menuItemSistemaFinanceiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSistemaFinanceiroActionPerformed

        Class_Verifica_Menu_Aberto verifica = new Class_Verifica_Menu_Aberto();
        int index = verifica.verificaMenuAberto(painel_principal, "Sistema financeiro   ");
        if (index >= 0)
        {
            painel_principal.setSelectedIndex(index);
        }
        else
        {
            Painel_Financeiro financeiro = new Painel_Financeiro(painel_principal, this.id_usuario, this.nome_usuario);
            painel_principal.addTab("Sistema financeiro   ", new ImageIcon(getClass().getResource("/imagens/Símbolo de dinheiro 16px.png")), financeiro, "Gerencie e configure o sistema financeiro!");
            painel_principal.setSelectedIndex(painel_principal.getTabCount()-1);
        }
        
    }//GEN-LAST:event_menuItemSistemaFinanceiroActionPerformed

    private void menuItemCadastroMesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadastroMesasActionPerformed
        
        Class_Verifica_Menu_Aberto verifica = new Class_Verifica_Menu_Aberto();
        int index = verifica.verificaMenuAberto(painel_principal, "Mesas   ");
        if (index >= 0)
        {
            painel_principal.setSelectedIndex(index);
        }
        else
        {
            Painel_Mesas mesas = new Painel_Mesas(painel_principal, this.id_usuario, this.nome_usuario);
            painel_principal.addTab("Mesas   ", new ImageIcon(getClass().getResource("/imagens/Mesa 16px.png")), mesas, "Gerencie o cadastro das mesas!");
            mesas.refreshList();
            painel_principal.setSelectedIndex(painel_principal.getTabCount()-1);
        }
        
    }//GEN-LAST:event_menuItemCadastroMesasActionPerformed

    private void menuItemCadastroClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadastroClientesActionPerformed
        
        Class_Verifica_Menu_Aberto verifica = new Class_Verifica_Menu_Aberto();
        int index = verifica.verificaMenuAberto(painel_principal, "Clientes   ");
        if (index >= 0)
        {
            painel_principal.setSelectedIndex(index);
        }
        else
        {
            Painel_Clientes clientes = new Painel_Clientes(painel_principal, this.id_usuario, this.nome_usuario);
            painel_principal.addTab("Clientes   ", new ImageIcon(getClass().getResource("/imagens/Cliente 16px.png")), clientes, "Gerencie o cadastro dos seus clientes!");
            clientes.refreshList();
            painel_principal.setSelectedIndex(painel_principal.getTabCount()-1);
        }
        
    }//GEN-LAST:event_menuItemCadastroClientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenu menuCadastros;
    private javax.swing.JMenu menuConfiguracoes;
    private javax.swing.JMenu menuEstoque;
    private javax.swing.JMenu menuFinanceiro;
    private javax.swing.JMenuItem menuItemCadastroClientes;
    private javax.swing.JMenuItem menuItemCadastroFornecedores;
    private javax.swing.JMenuItem menuItemCadastroMesas;
    private javax.swing.JMenuItem menuItemCadastroProdutos;
    private javax.swing.JMenuItem menuItemCadastroUsuarios;
    private javax.swing.JMenuItem menuItemCentrosCusto;
    private javax.swing.JMenuItem menuItemCentrosEstoque;
    private javax.swing.JMenuItem menuItemCompras;
    private javax.swing.JMenuItem menuItemConfiguracoesSistema;
    private javax.swing.JMenuItem menuItemSair;
    private javax.swing.JMenuItem menuItemSistemaFinanceiro;
    private javax.swing.JMenuItem menuItemTrocarUsuario;
    private javax.swing.JMenuItem menuItemVenda;
    private javax.swing.JMenu menuRelatorios;
    private javax.swing.JMenu menuRelatoriosAuditoria;
    private javax.swing.JMenu menuRelatoriosFinanceiro;
    private javax.swing.JMenu menuRelatoriosUsuarios;
    private javax.swing.JMenu menuRelatoriosVendas;
    private javax.swing.JMenu menuSistema;
    private javax.swing.JTabbedPane painel_principal;
    // End of variables declaration//GEN-END:variables
}
