
package financeiro;

import centros_custo.Class_Caixa;
import centros_custo.Class_Centros_Custo;
import principal.Class_Consumir_Letras;
import principal.Class_Verifica_Menu_Aberto;
import formas_pagamento.Class_Formas_Pagto;
import usuarios.Class_Usuarios;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.ListModel;
import javax.swing.table.DefaultTableModel;

public class Painel_Financeiro extends javax.swing.JPanel {

    protected JTabbedPane painel_principal;
    protected int id_usuario;
    protected String nome_usuario;
    protected String id_centro_custo;
    
    public Painel_Financeiro(JTabbedPane painel_principal, int id_usuario, String nome_usuario) {
        initComponents();
        
        this.painel_principal = painel_principal;
        this.id_usuario = id_usuario;
        this.nome_usuario = nome_usuario;
    }
    
    public void carregaLancamentos() {
        int flagReceita = 0, flagDespesa = 0;
        String liquidado = comboSituacaoLancamentos.getSelectedItem().toString(), data_de, data_ate;
        
        //PRIMEIRO VERIFICO O QUE DEVO PESQUISAR (TODOS, RECEITA OU DESPESA).
        String pesquisa = comboPesquisaLancamentos.getSelectedItem().toString();
        if (pesquisa.equals("Todos")) {
            flagReceita = 1;
            flagDespesa = 1;
        } else if (pesquisa.equals("Receita")) {
            flagReceita = 1;
        } else {
            flagDespesa = 1;
        }
        
        //REALIZO A FORMATAÇÃO DAS DATAS PARA A PESQUISA.
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        data_de = sdf.format(dataPesquisa1Lancamentos.getDate());
        data_ate = sdf.format(dataPesquisa2Lancamentos.getDate());
        
        //AGORA FAÇO A PESQUISA.
        DefaultTableModel modelo = (DefaultTableModel) tabelaLancamentos.getModel();
        modelo.setRowCount(0);
        if (flagReceita == 1) {
            Class_Receitas receitas = new Class_Receitas();
            receitas.carregaReceitas(liquidado, data_de, data_ate, modelo);
        }
        if (flagDespesa == 1) {
            Class_Despesas despesas = new Class_Despesas();
            despesas.carregaDespesas(liquidado, data_de, data_ate, modelo);
        }
    }
    
    public void limpaCamposNovoLancamento() {
        comboTipoNovoLancamento.setSelectedIndex(0);
        txtDescricaoNovoLancamento.setText("");
        txtValorNovoLancamento.setText("");
        comboParcelasNovoLancamento.setSelectedIndex(0);
        txtDescricaoNovoLancamento.grabFocus();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Centros_Custo = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista_centros_custo = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtNomeCentro = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtSaldoCentro = new javax.swing.JTextField();
        btnNovoCentroCusto = new javax.swing.JButton();
        btnAlterarCentrosCusto = new javax.swing.JButton();
        btnExcluirCentrosCusto = new javax.swing.JButton();
        btnSairCentrosCusto = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txtTipoCentroCusto = new javax.swing.JTextField();
        Novo_Centro_Custo = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNomeCentro1 = new javax.swing.JTextField();
        btnSalvarCentroCusto = new javax.swing.JButton();
        btnSairCadastroCentroCusto = new javax.swing.JButton();
        btnLimparDadosCentroCusto = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        radioCaixa = new javax.swing.JRadioButton();
        radioContaBancaria = new javax.swing.JRadioButton();
        Alterar_Centro_Custo = new javax.swing.JDialog();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtNomeCentro2 = new javax.swing.JTextField();
        btnSalvarCentroCusto2 = new javax.swing.JButton();
        btnSairCadastroCentroCusto2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        lblTipoCentroCusto = new javax.swing.JLabel();
        Configurar_Responsaveis_Caixa = new javax.swing.JDialog();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lista_caixas = new javax.swing.JList();
        jLabel19 = new javax.swing.JLabel();
        comboUsuario = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        lblCaixaSelecionado = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lista_responsaveis = new javax.swing.JList();
        btnSairConfiguracaoResponsaveis = new javax.swing.JButton();
        btnRetirarResponsavelCaixa = new javax.swing.JButton();
        btnAdicionarResponsavelCaixa = new javax.swing.JButton();
        Lancamentos = new javax.swing.JDialog();
        jLabel23 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        comboPesquisaLancamentos = new javax.swing.JComboBox();
        jLabel29 = new javax.swing.JLabel();
        dataPesquisa1Lancamentos = new com.toedter.calendar.JDateChooser();
        jLabel30 = new javax.swing.JLabel();
        dataPesquisa2Lancamentos = new com.toedter.calendar.JDateChooser();
        jLabel31 = new javax.swing.JLabel();
        comboSituacaoLancamentos = new javax.swing.JComboBox();
        btnPesquisarLancamento = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelaLancamentos = new javax.swing.JTable();
        btmLiquidarLancamentos = new javax.swing.JButton();
        btnAlterarLancamentos = new javax.swing.JButton();
        btnNovoLancamentos = new javax.swing.JButton();
        btnExcluirLancamentos = new javax.swing.JButton();
        btnSairLancamentos = new javax.swing.JButton();
        btnDesliquidarLancamentos = new javax.swing.JButton();
        Agendar_Lancamento = new javax.swing.JDialog();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtDescricaoNovoLancamento = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        comboTipoNovoLancamento = new javax.swing.JComboBox();
        jLabel32 = new javax.swing.JLabel();
        txtValorNovoLancamento = new javax.swing.JTextField();
        btnSalvarNovoLancamento = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnSairNovoLancamento = new javax.swing.JButton();
        comboFormaNovoLancamento = new javax.swing.JComboBox();
        jLabel33 = new javax.swing.JLabel();
        comboParcelasNovoLancamento = new javax.swing.JComboBox();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnCentrosCusto = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btnConfigurarCentros = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        btnLancamentos = new javax.swing.JButton();
        btnSairPainelFinanceiro = new javax.swing.JButton();

        Centros_Custo.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        Centros_Custo.setTitle("Manutenção do cadastro de centros de custo");
        Centros_Custo.setModal(true);
        Centros_Custo.setResizable(false);
        Centros_Custo.getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/dollar122 (2).png"))); // NOI18N
        jLabel4.setText("Manutenção do cadastro de centros de custo");
        Centros_Custo.getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 30, 610, 30);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Centros de custo");
        Centros_Custo.getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 90, 110, 17);

        jScrollPane1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lista_centros_custo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lista_centros_custo.setSelectionBackground(new java.awt.Color(204, 255, 255));
        lista_centros_custo.setSelectionForeground(new java.awt.Color(0, 0, 0));
        lista_centros_custo.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lista_centros_custoValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lista_centros_custo);

        Centros_Custo.getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 110, 220, 230);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/magnifier12.png"))); // NOI18N
        Centros_Custo.getContentPane().add(jButton1);
        jButton1.setBounds(200, 80, 40, 30);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Nome");
        Centros_Custo.getContentPane().add(jLabel6);
        jLabel6.setBounds(300, 120, 40, 17);

        txtNomeCentro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNomeCentro.setEnabled(false);
        Centros_Custo.getContentPane().add(txtNomeCentro);
        txtNomeCentro.setBounds(350, 110, 240, 30);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Saldo");
        Centros_Custo.getContentPane().add(jLabel7);
        jLabel7.setBounds(300, 200, 40, 17);

        txtSaldoCentro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtSaldoCentro.setEnabled(false);
        Centros_Custo.getContentPane().add(txtSaldoCentro);
        txtSaldoCentro.setBounds(350, 190, 240, 30);

        btnNovoCentroCusto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnNovoCentroCusto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/plus24.png"))); // NOI18N
        btnNovoCentroCusto.setText("Novo");
        btnNovoCentroCusto.setToolTipText("Cadastrar novo centro de custo");
        btnNovoCentroCusto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoCentroCustoActionPerformed(evt);
            }
        });
        Centros_Custo.getContentPane().add(btnNovoCentroCusto);
        btnNovoCentroCusto.setBounds(90, 390, 100, 30);

        btnAlterarCentrosCusto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnAlterarCentrosCusto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/drawing4.png"))); // NOI18N
        btnAlterarCentrosCusto.setText("Alterar");
        btnAlterarCentrosCusto.setToolTipText("Alterar centro de custo existente");
        btnAlterarCentrosCusto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarCentrosCustoActionPerformed(evt);
            }
        });
        Centros_Custo.getContentPane().add(btnAlterarCentrosCusto);
        btnAlterarCentrosCusto.setBounds(200, 390, 100, 30);

        btnExcluirCentrosCusto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnExcluirCentrosCusto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/prohibition9.png"))); // NOI18N
        btnExcluirCentrosCusto.setText("Excluir");
        btnExcluirCentrosCusto.setToolTipText("Excluir centro de custo");
        btnExcluirCentrosCusto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirCentrosCustoActionPerformed(evt);
            }
        });
        Centros_Custo.getContentPane().add(btnExcluirCentrosCusto);
        btnExcluirCentrosCusto.setBounds(310, 390, 100, 30);

        btnSairCentrosCusto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSairCentrosCusto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/man349.png"))); // NOI18N
        btnSairCentrosCusto.setText("Sair");
        btnSairCentrosCusto.setToolTipText("Fechar a tela de centros de custo");
        btnSairCentrosCusto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairCentrosCustoActionPerformed(evt);
            }
        });
        Centros_Custo.getContentPane().add(btnSairCentrosCusto);
        btnSairCentrosCusto.setBounds(420, 390, 100, 30);

        jLabel14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel14.setText("  Tipo");
        Centros_Custo.getContentPane().add(jLabel14);
        jLabel14.setBounds(300, 160, 40, 20);

        txtTipoCentroCusto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTipoCentroCusto.setEnabled(false);
        Centros_Custo.getContentPane().add(txtTipoCentroCusto);
        txtTipoCentroCusto.setBounds(350, 150, 240, 30);

        Novo_Centro_Custo.setTitle("Novo cadastro");
        Novo_Centro_Custo.setModal(true);
        Novo_Centro_Custo.setResizable(false);
        Novo_Centro_Custo.getContentPane().setLayout(null);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/dollar122 (1).png"))); // NOI18N
        jLabel8.setText("Cadastrar centro de custo");
        Novo_Centro_Custo.getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 20, 420, 30);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("Nome");
        Novo_Centro_Custo.getContentPane().add(jLabel9);
        jLabel9.setBounds(50, 90, 40, 17);

        txtNomeCentro1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Novo_Centro_Custo.getContentPane().add(txtNomeCentro1);
        txtNomeCentro1.setBounds(100, 80, 240, 30);

        btnSalvarCentroCusto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSalvarCentroCusto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/white65.png"))); // NOI18N
        btnSalvarCentroCusto.setText("Salvar");
        btnSalvarCentroCusto.setToolTipText("Salvar o cadastro do centro de custo");
        btnSalvarCentroCusto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarCentroCustoActionPerformed(evt);
            }
        });
        Novo_Centro_Custo.getContentPane().add(btnSalvarCentroCusto);
        btnSalvarCentroCusto.setBounds(50, 190, 100, 30);

        btnSairCadastroCentroCusto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSairCadastroCentroCusto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/man349.png"))); // NOI18N
        btnSairCadastroCentroCusto.setText("Sair");
        btnSairCadastroCentroCusto.setToolTipText("Cancelar cadastro");
        btnSairCadastroCentroCusto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairCadastroCentroCustoActionPerformed(evt);
            }
        });
        Novo_Centro_Custo.getContentPane().add(btnSairCadastroCentroCusto);
        btnSairCadastroCentroCusto.setBounds(270, 190, 100, 30);

        btnLimparDadosCentroCusto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnLimparDadosCentroCusto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/drawing4.png"))); // NOI18N
        btnLimparDadosCentroCusto.setText("Limpar");
        btnLimparDadosCentroCusto.setToolTipText("Limpar dados e recomeçar cadastro");
        btnLimparDadosCentroCusto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparDadosCentroCustoActionPerformed(evt);
            }
        });
        Novo_Centro_Custo.getContentPane().add(btnLimparDadosCentroCusto);
        btnLimparDadosCentroCusto.setBounds(160, 190, 100, 30);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("  Tipo");
        Novo_Centro_Custo.getContentPane().add(jLabel10);
        jLabel10.setBounds(50, 130, 40, 20);

        radioCaixa.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        radioCaixa.setText("Caixa");
        radioCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCaixaActionPerformed(evt);
            }
        });
        Novo_Centro_Custo.getContentPane().add(radioCaixa);
        radioCaixa.setBounds(120, 120, 70, 40);

        radioContaBancaria.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        radioContaBancaria.setText("Conta bancária");
        radioContaBancaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioContaBancariaActionPerformed(evt);
            }
        });
        Novo_Centro_Custo.getContentPane().add(radioContaBancaria);
        radioContaBancaria.setBounds(200, 120, 130, 40);

        Alterar_Centro_Custo.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        Alterar_Centro_Custo.setTitle("Alteração de dados");
        Alterar_Centro_Custo.setModal(true);
        Alterar_Centro_Custo.setResizable(false);
        Alterar_Centro_Custo.getContentPane().setLayout(null);

        jLabel12.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/dollar122 (1).png"))); // NOI18N
        jLabel12.setText("Alterar centro de custo");
        Alterar_Centro_Custo.getContentPane().add(jLabel12);
        jLabel12.setBounds(0, 20, 420, 30);

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setText("Nome");
        Alterar_Centro_Custo.getContentPane().add(jLabel13);
        jLabel13.setBounds(50, 90, 40, 17);

        txtNomeCentro2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Alterar_Centro_Custo.getContentPane().add(txtNomeCentro2);
        txtNomeCentro2.setBounds(100, 80, 240, 30);

        btnSalvarCentroCusto2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSalvarCentroCusto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/white65.png"))); // NOI18N
        btnSalvarCentroCusto2.setText("Salvar");
        btnSalvarCentroCusto2.setToolTipText("Salvar alterações");
        btnSalvarCentroCusto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarCentroCusto2ActionPerformed(evt);
            }
        });
        Alterar_Centro_Custo.getContentPane().add(btnSalvarCentroCusto2);
        btnSalvarCentroCusto2.setBounds(100, 170, 100, 30);

        btnSairCadastroCentroCusto2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSairCadastroCentroCusto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/man349.png"))); // NOI18N
        btnSairCadastroCentroCusto2.setText("Sair");
        btnSairCadastroCentroCusto2.setToolTipText("Cancelar alterações");
        btnSairCadastroCentroCusto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairCadastroCentroCusto2ActionPerformed(evt);
            }
        });
        Alterar_Centro_Custo.getContentPane().add(btnSairCadastroCentroCusto2);
        btnSairCadastroCentroCusto2.setBounds(210, 170, 100, 30);

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("Tipo do centro de custo:");
        Alterar_Centro_Custo.getContentPane().add(jLabel11);
        jLabel11.setBounds(60, 130, 160, 20);

        lblTipoCentroCusto.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTipoCentroCusto.setForeground(new java.awt.Color(255, 0, 0));
        lblTipoCentroCusto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTipoCentroCusto.setText("Conta bancária");
        Alterar_Centro_Custo.getContentPane().add(lblTipoCentroCusto);
        lblTipoCentroCusto.setBounds(220, 130, 110, 20);

        Configurar_Responsaveis_Caixa.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        Configurar_Responsaveis_Caixa.setTitle("Configurar responsáveis pelo caixa");
        Configurar_Responsaveis_Caixa.setModal(true);
        Configurar_Responsaveis_Caixa.setResizable(false);
        Configurar_Responsaveis_Caixa.getContentPane().setLayout(null);

        jLabel17.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/coins15 (1).png"))); // NOI18N
        jLabel17.setText("Configuração dos responsáveis pelos caixas");
        Configurar_Responsaveis_Caixa.getContentPane().add(jLabel17);
        jLabel17.setBounds(0, 30, 650, 30);

        jLabel18.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel18.setText("Caixas disponíveis");
        Configurar_Responsaveis_Caixa.getContentPane().add(jLabel18);
        jLabel18.setBounds(20, 90, 120, 17);

        lista_caixas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lista_caixas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        lista_caixas.setToolTipText("");
        lista_caixas.setSelectionBackground(new java.awt.Color(204, 255, 255));
        lista_caixas.setSelectionForeground(new java.awt.Color(0, 0, 0));
        lista_caixas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lista_caixasValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lista_caixas);

        Configurar_Responsaveis_Caixa.getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(20, 110, 200, 250);

        jLabel19.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel19.setText("Selecione um usuário para adicionar aos responsáveis");
        Configurar_Responsaveis_Caixa.getContentPane().add(jLabel19);
        jLabel19.setBounds(280, 90, 350, 17);

        comboUsuario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        comboUsuario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Selecione>" }));
        comboUsuario.setToolTipText("Selecione um usuário para adicionar como responsável");
        Configurar_Responsaveis_Caixa.getContentPane().add(comboUsuario);
        comboUsuario.setBounds(280, 110, 350, 30);

        jLabel20.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel20.setText("Responsáveis pelo caixa");
        Configurar_Responsaveis_Caixa.getContentPane().add(jLabel20);
        jLabel20.setBounds(280, 190, 170, 17);

        lblCaixaSelecionado.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblCaixaSelecionado.setForeground(new java.awt.Color(255, 0, 0));
        lblCaixaSelecionado.setText("Caixa selecionado");
        Configurar_Responsaveis_Caixa.getContentPane().add(lblCaixaSelecionado);
        lblCaixaSelecionado.setBounds(450, 190, 180, 17);

        lista_responsaveis.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lista_responsaveis.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        lista_responsaveis.setToolTipText("Responsável pelo caixa selecionado");
        lista_responsaveis.setSelectionBackground(new java.awt.Color(204, 255, 255));
        lista_responsaveis.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane3.setViewportView(lista_responsaveis);

        Configurar_Responsaveis_Caixa.getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(280, 210, 350, 150);

        btnSairConfiguracaoResponsaveis.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSairConfiguracaoResponsaveis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/man349.png"))); // NOI18N
        btnSairConfiguracaoResponsaveis.setText("Sair");
        btnSairConfiguracaoResponsaveis.setToolTipText("Fechar a tela de configuração dos responsáveis pelos caixas");
        btnSairConfiguracaoResponsaveis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairConfiguracaoResponsaveisActionPerformed(evt);
            }
        });
        Configurar_Responsaveis_Caixa.getContentPane().add(btnSairConfiguracaoResponsaveis);
        btnSairConfiguracaoResponsaveis.setBounds(280, 410, 100, 30);

        btnRetirarResponsavelCaixa.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnRetirarResponsavelCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/prohibition9.png"))); // NOI18N
        btnRetirarResponsavelCaixa.setText("Retirar");
        btnRetirarResponsavelCaixa.setToolTipText("Retirar responsáveis do caixa");
        btnRetirarResponsavelCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarResponsavelCaixaActionPerformed(evt);
            }
        });
        Configurar_Responsaveis_Caixa.getContentPane().add(btnRetirarResponsavelCaixa);
        btnRetirarResponsavelCaixa.setBounds(510, 140, 120, 30);

        btnAdicionarResponsavelCaixa.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnAdicionarResponsavelCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/white65.png"))); // NOI18N
        btnAdicionarResponsavelCaixa.setText("Adicionar");
        btnAdicionarResponsavelCaixa.setToolTipText("Adicionar responsáveis ao caixa selecionado");
        btnAdicionarResponsavelCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarResponsavelCaixaActionPerformed(evt);
            }
        });
        Configurar_Responsaveis_Caixa.getContentPane().add(btnAdicionarResponsavelCaixa);
        btnAdicionarResponsavelCaixa.setBounds(380, 140, 120, 30);

        Lancamentos.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        Lancamentos.setTitle("Gerenciamento de receitas e despesas");
        Lancamentos.setModal(true);
        Lancamentos.setResizable(false);
        Lancamentos.getContentPane().setLayout(null);

        jLabel23.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/dollar130 (1).png"))); // NOI18N
        jLabel23.setText("Manutenção do gerenciamento de receitas e despesas");
        Lancamentos.getContentPane().add(jLabel23);
        jLabel23.setBounds(0, 30, 1000, 30);

        jLabel28.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel28.setText("A pesquisar");
        Lancamentos.getContentPane().add(jLabel28);
        jLabel28.setBounds(20, 100, 80, 17);

        comboPesquisaLancamentos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        comboPesquisaLancamentos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos", "Receita", "Despesa" }));
        Lancamentos.getContentPane().add(comboPesquisaLancamentos);
        comboPesquisaLancamentos.setBounds(110, 90, 120, 30);

        jLabel29.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel29.setText("Período");
        Lancamentos.getContentPane().add(jLabel29);
        jLabel29.setBounds(270, 100, 49, 17);

        dataPesquisa1Lancamentos.setDate(new Date());
        dataPesquisa1Lancamentos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Lancamentos.getContentPane().add(dataPesquisa1Lancamentos);
        dataPesquisa1Lancamentos.setBounds(330, 90, 140, 30);

        jLabel30.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel30.setText("Até");
        Lancamentos.getContentPane().add(jLabel30);
        jLabel30.setBounds(490, 100, 21, 17);

        dataPesquisa2Lancamentos.setDate(new Date());
        dataPesquisa2Lancamentos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Lancamentos.getContentPane().add(dataPesquisa2Lancamentos);
        dataPesquisa2Lancamentos.setBounds(530, 90, 140, 30);

        jLabel31.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel31.setText("Situação");
        Lancamentos.getContentPane().add(jLabel31);
        jLabel31.setBounds(710, 100, 55, 17);

        comboSituacaoLancamentos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        comboSituacaoLancamentos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos", "Liquidado", "Não liquidado" }));
        Lancamentos.getContentPane().add(comboSituacaoLancamentos);
        comboSituacaoLancamentos.setBounds(780, 90, 130, 30);

        btnPesquisarLancamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/magnifier12.png"))); // NOI18N
        btnPesquisarLancamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarLancamentoActionPerformed(evt);
            }
        });
        Lancamentos.getContentPane().add(btnPesquisarLancamento);
        btnPesquisarLancamento.setBounds(930, 90, 49, 30);

        tabelaLancamentos.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tabelaLancamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Descrição", "Forma Pagto", "Valor", "Parcelas", "Vencimento", "Liquidado", "Tipo", "Cod"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaLancamentos.setRowHeight(25);
        tabelaLancamentos.setSelectionBackground(new java.awt.Color(204, 255, 255));
        tabelaLancamentos.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane4.setViewportView(tabelaLancamentos);
        if (tabelaLancamentos.getColumnModel().getColumnCount() > 0) {
            tabelaLancamentos.getColumnModel().getColumn(0).setPreferredWidth(300);
            tabelaLancamentos.getColumnModel().getColumn(1).setPreferredWidth(200);
            tabelaLancamentos.getColumnModel().getColumn(2).setPreferredWidth(80);
            tabelaLancamentos.getColumnModel().getColumn(3).setPreferredWidth(50);
            tabelaLancamentos.getColumnModel().getColumn(4).setPreferredWidth(70);
            tabelaLancamentos.getColumnModel().getColumn(5).setPreferredWidth(50);
            tabelaLancamentos.getColumnModel().getColumn(6).setPreferredWidth(50);
            tabelaLancamentos.getColumnModel().getColumn(7).setPreferredWidth(30);
        }

        Lancamentos.getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(20, 150, 960, 310);

        btmLiquidarLancamentos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btmLiquidarLancamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/white65.png"))); // NOI18N
        btmLiquidarLancamentos.setText("Liquidar");
        btmLiquidarLancamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmLiquidarLancamentosActionPerformed(evt);
            }
        });
        Lancamentos.getContentPane().add(btmLiquidarLancamentos);
        btmLiquidarLancamentos.setBounds(80, 500, 130, 30);

        btnAlterarLancamentos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnAlterarLancamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/drawing4.png"))); // NOI18N
        btnAlterarLancamentos.setText("Alterar");
        Lancamentos.getContentPane().add(btnAlterarLancamentos);
        btnAlterarLancamentos.setBounds(500, 500, 130, 30);

        btnNovoLancamentos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnNovoLancamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/plus24.png"))); // NOI18N
        btnNovoLancamentos.setText("Agendar");
        btnNovoLancamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoLancamentosActionPerformed(evt);
            }
        });
        Lancamentos.getContentPane().add(btnNovoLancamentos);
        btnNovoLancamentos.setBounds(360, 500, 130, 30);

        btnExcluirLancamentos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnExcluirLancamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/prohibition9.png"))); // NOI18N
        btnExcluirLancamentos.setText("Excluir");
        Lancamentos.getContentPane().add(btnExcluirLancamentos);
        btnExcluirLancamentos.setBounds(640, 500, 130, 30);

        btnSairLancamentos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSairLancamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/man349.png"))); // NOI18N
        btnSairLancamentos.setText("Sair");
        Lancamentos.getContentPane().add(btnSairLancamentos);
        btnSairLancamentos.setBounds(780, 500, 130, 30);

        btnDesliquidarLancamentos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnDesliquidarLancamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/curve20.png"))); // NOI18N
        btnDesliquidarLancamentos.setText("Desliquidar");
        btnDesliquidarLancamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesliquidarLancamentosActionPerformed(evt);
            }
        });
        Lancamentos.getContentPane().add(btnDesliquidarLancamentos);
        btnDesliquidarLancamentos.setBounds(220, 500, 130, 30);

        Agendar_Lancamento.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        Agendar_Lancamento.setTitle("Lançamento avulso na conta bancária");
        Agendar_Lancamento.setModal(true);
        Agendar_Lancamento.setResizable(false);
        Agendar_Lancamento.getContentPane().setLayout(null);

        jLabel24.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/coins15.png"))); // NOI18N
        jLabel24.setText("Novo agendamento");
        Agendar_Lancamento.getContentPane().add(jLabel24);
        jLabel24.setBounds(0, 30, 671, 30);

        jLabel25.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel25.setText("Descrição do lançamento");
        Agendar_Lancamento.getContentPane().add(jLabel25);
        jLabel25.setBounds(40, 150, 170, 17);

        txtDescricaoNovoLancamento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Agendar_Lancamento.getContentPane().add(txtDescricaoNovoLancamento);
        txtDescricaoNovoLancamento.setBounds(220, 140, 410, 30);

        jLabel26.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel26.setText(" Forma de pagamento");
        Agendar_Lancamento.getContentPane().add(jLabel26);
        jLabel26.setBounds(60, 190, 150, 17);

        jLabel27.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel27.setText(" Tipo de lançamento");
        Agendar_Lancamento.getContentPane().add(jLabel27);
        jLabel27.setBounds(70, 110, 140, 17);

        comboTipoNovoLancamento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        comboTipoNovoLancamento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Receita", "Despesa" }));
        comboTipoNovoLancamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoNovoLancamentoActionPerformed(evt);
            }
        });
        Agendar_Lancamento.getContentPane().add(comboTipoNovoLancamento);
        comboTipoNovoLancamento.setBounds(220, 100, 410, 30);

        jLabel32.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel32.setText("Valor do lançamento");
        Agendar_Lancamento.getContentPane().add(jLabel32);
        jLabel32.setBounds(70, 230, 140, 17);

        txtValorNovoLancamento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtValorNovoLancamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValorNovoLancamentoKeyTyped(evt);
            }
        });
        Agendar_Lancamento.getContentPane().add(txtValorNovoLancamento);
        txtValorNovoLancamento.setBounds(220, 220, 130, 30);

        btnSalvarNovoLancamento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSalvarNovoLancamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/white65.png"))); // NOI18N
        btnSalvarNovoLancamento.setText("Salvar");
        btnSalvarNovoLancamento.setToolTipText("Cadastra a receita na conta bancária");
        btnSalvarNovoLancamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarNovoLancamentoActionPerformed(evt);
            }
        });
        Agendar_Lancamento.getContentPane().add(btnSalvarNovoLancamento);
        btnSalvarNovoLancamento.setBounds(180, 370, 100, 30);

        btnLimpar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/drawing4.png"))); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.setToolTipText("Limpa os campos para recomeçar o lançamento");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        Agendar_Lancamento.getContentPane().add(btnLimpar);
        btnLimpar.setBounds(290, 370, 100, 30);

        btnSairNovoLancamento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSairNovoLancamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/man349.png"))); // NOI18N
        btnSairNovoLancamento.setText("Sair");
        btnSairNovoLancamento.setToolTipText("Cancelar lançamento na conta bancária");
        btnSairNovoLancamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairNovoLancamentoActionPerformed(evt);
            }
        });
        Agendar_Lancamento.getContentPane().add(btnSairNovoLancamento);
        btnSairNovoLancamento.setBounds(400, 370, 100, 30);

        comboFormaNovoLancamento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Agendar_Lancamento.getContentPane().add(comboFormaNovoLancamento);
        comboFormaNovoLancamento.setBounds(220, 180, 410, 30);

        jLabel33.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel33.setText(" Número de parcelas");
        Agendar_Lancamento.getContentPane().add(jLabel33);
        jLabel33.setBounds(400, 230, 140, 17);

        comboParcelasNovoLancamento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        comboParcelasNovoLancamento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        Agendar_Lancamento.getContentPane().add(comboParcelasNovoLancamento);
        comboParcelasNovoLancamento.setBounds(560, 220, 70, 30);

        jLabel34.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 0, 0));
        jLabel34.setText("Obs: Este agendamento irá gerar uma receita ou despesa não liquidados!");
        Agendar_Lancamento.getContentPane().add(jLabel34);
        jLabel34.setBounds(80, 330, 520, 17);

        jLabel35.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel35.setText("Cliente / Responsável");
        Agendar_Lancamento.getContentPane().add(jLabel35);
        jLabel35.setBounds(60, 270, 150, 17);

        jComboBox1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Selecione>" }));
        Agendar_Lancamento.getContentPane().add(jComboBox1);
        jComboBox1.setBounds(220, 260, 410, 30);

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/coin12 (1).png"))); // NOI18N
        jLabel1.setText("Manutenção do sistema financeiro");
        add(jLabel1);
        jLabel1.setBounds(0, 30, 760, 30);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Cadastre centros de custo para");
        add(jLabel2);
        jLabel2.setBounds(20, 110, 200, 17);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("gerenciar melhor seu dinheiro");
        add(jLabel3);
        jLabel3.setBounds(20, 130, 190, 17);

        btnCentrosCusto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnCentrosCusto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/dollar122 (1).png"))); // NOI18N
        btnCentrosCusto.setText("Centros de custo");
        btnCentrosCusto.setToolTipText("Cadastre os centros de custo!");
        btnCentrosCusto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCentrosCustoActionPerformed(evt);
            }
        });
        add(btnCentrosCusto);
        btnCentrosCusto.setBounds(20, 160, 170, 30);

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setText("Defina os responsáveis por cada");
        add(jLabel15);
        jLabel15.setBounds(20, 230, 210, 17);

        jLabel16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel16.setText("caixa existente no sistema");
        add(jLabel16);
        jLabel16.setBounds(20, 250, 170, 17);

        btnConfigurarCentros.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnConfigurarCentros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/three115.png"))); // NOI18N
        btnConfigurarCentros.setText("Configurações");
        btnConfigurarCentros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfigurarCentrosActionPerformed(evt);
            }
        });
        add(btnConfigurarCentros);
        btnConfigurarCentros.setBounds(20, 280, 170, 30);

        jLabel21.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel21.setText("Gerencie suas receitas e despesas");
        add(jLabel21);
        jLabel21.setBounds(270, 110, 230, 17);

        jLabel22.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel22.setText("e agende lançamentos");
        add(jLabel22);
        jLabel22.setBounds(270, 130, 144, 17);

        btnLancamentos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnLancamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/dollar130.png"))); // NOI18N
        btnLancamentos.setText("Lançamentos");
        btnLancamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLancamentosActionPerformed(evt);
            }
        });
        add(btnLancamentos);
        btnLancamentos.setBounds(270, 160, 170, 30);

        btnSairPainelFinanceiro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSairPainelFinanceiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barsystems/imagens/man349.png"))); // NOI18N
        btnSairPainelFinanceiro.setText("Sair");
        btnSairPainelFinanceiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairPainelFinanceiroActionPerformed(evt);
            }
        });
        add(btnSairPainelFinanceiro);
        btnSairPainelFinanceiro.setBounds(300, 350, 110, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCentrosCustoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCentrosCustoActionPerformed
        
        txtNomeCentro.setText("");
        txtTipoCentroCusto.setText("");
        txtSaldoCentro.setText("");
        Class_Centros_Custo centro_custo = new Class_Centros_Custo();
        lista_centros_custo.setModel(centro_custo.carregaLista());
        Centros_Custo.setBounds(0, 0, 630, 480);
        Centros_Custo.setLocationRelativeTo(null);
        Centros_Custo.setVisible(true);
        
    }//GEN-LAST:event_btnCentrosCustoActionPerformed

    private void btnNovoCentroCustoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoCentroCustoActionPerformed
        
        txtNomeCentro1.setText("");
        Novo_Centro_Custo.setBounds(0, 0, 430, 290);
        Novo_Centro_Custo.setLocationRelativeTo(null);
        Novo_Centro_Custo.setVisible(true);
        txtNomeCentro1.grabFocus();
        
    }//GEN-LAST:event_btnNovoCentroCustoActionPerformed

    private void btnSalvarCentroCustoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarCentroCustoActionPerformed
        
        if (txtNomeCentro1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Não pode haver campos vazios!", "Atenção", JOptionPane.WARNING_MESSAGE);
            txtNomeCentro1.grabFocus();
        } else if (!radioCaixa.isSelected() && !radioContaBancaria.isSelected()) {
            JOptionPane.showMessageDialog(null, "Selecione o tipo do centro de custo!", "Atenção", JOptionPane.WARNING_MESSAGE);
        } else {
            String tipo;
            if (radioCaixa.isSelected()) {
                tipo = "Caixa";
            } else {
                tipo = "Conta bancária";
            }
            Class_Centros_Custo centro_custo = new Class_Centros_Custo();
            centro_custo.Cadastra(txtNomeCentro1.getText(), tipo);
            Novo_Centro_Custo.dispose();
            lista_centros_custo.setModel(centro_custo.carregaLista());
            txtNomeCentro.setText("");
            txtTipoCentroCusto.setText("");
            txtSaldoCentro.setText("");
        }
        
    }//GEN-LAST:event_btnSalvarCentroCustoActionPerformed

    private void btnAlterarCentrosCustoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarCentrosCustoActionPerformed
        
        Object centro_custo = lista_centros_custo.getSelectedValue();
        if (centro_custo == null) {
            JOptionPane.showMessageDialog(null, "Selecione um centro de custo para alterar!", "Atenção", JOptionPane.WARNING_MESSAGE);
        } else {
            txtNomeCentro2.setText(txtNomeCentro.getText());
            lblTipoCentroCusto.setText(txtTipoCentroCusto.getText());
            Alterar_Centro_Custo.setBounds(0, 0, 420, 250);
            Alterar_Centro_Custo.setLocationRelativeTo(null);
            Alterar_Centro_Custo.setVisible(true);
            txtNomeCentro2.grabFocus();
        }
        
    }//GEN-LAST:event_btnAlterarCentrosCustoActionPerformed

    private void btnLimparDadosCentroCustoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparDadosCentroCustoActionPerformed
        
        txtNomeCentro1.setText("");
        radioCaixa.setSelected(false);
        radioContaBancaria.setSelected(false);
        txtNomeCentro1.grabFocus();
        
    }//GEN-LAST:event_btnLimparDadosCentroCustoActionPerformed

    private void btnSalvarCentroCusto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarCentroCusto2ActionPerformed
        
        if (txtNomeCentro2.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Não pode haver campos vazios!", "Atenção", JOptionPane.WARNING_MESSAGE);
            txtNomeCentro2.grabFocus();
        } else {
            Class_Centros_Custo centro_custo = new Class_Centros_Custo();
            centro_custo.edita(id_centro_custo, txtNomeCentro2.getText());
            Alterar_Centro_Custo.dispose();
            lista_centros_custo.setModel(centro_custo.carregaLista());
            txtNomeCentro.setText("");
            txtTipoCentroCusto.setText("");
            txtSaldoCentro.setText("");
        }
        
    }//GEN-LAST:event_btnSalvarCentroCusto2ActionPerformed

    private void lista_centros_custoValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lista_centros_custoValueChanged
        
        Object centroCusto = lista_centros_custo.getSelectedValue();
        if (centroCusto != null) {
            Class_Centros_Custo centros_custo = new Class_Centros_Custo();
            centros_custo.carregaCentroCusto(centroCusto.toString());
            id_centro_custo = centros_custo.getIdCentroCusto();
            txtNomeCentro.setText(centros_custo.getNomeCentroCusto());
            txtTipoCentroCusto.setText(centros_custo.getTipoCentroCusto());
            txtSaldoCentro.setText(centros_custo.getSaldoCentroCusto());
        }
        
    }//GEN-LAST:event_lista_centros_custoValueChanged

    private void btnSairCadastroCentroCustoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairCadastroCentroCustoActionPerformed
        
        Novo_Centro_Custo.dispose();
        
    }//GEN-LAST:event_btnSairCadastroCentroCustoActionPerformed

    private void btnSairCadastroCentroCusto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairCadastroCentroCusto2ActionPerformed
        
        Alterar_Centro_Custo.dispose();
        
    }//GEN-LAST:event_btnSairCadastroCentroCusto2ActionPerformed

    private void btnExcluirCentrosCustoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirCentrosCustoActionPerformed
        
        Object centro_custo = lista_centros_custo.getSelectedValue();
        if (centro_custo == null) {
            JOptionPane.showMessageDialog(null, "Selecione um centro de custo para excluir!", "Atenção", JOptionPane.WARNING_MESSAGE);
        } else {
            if (JOptionPane.showConfirmDialog(null, "Deseja realmente excluir?", "Atenção", JOptionPane.YES_NO_OPTION) == 0) {
                Class_Centros_Custo centros_custo = new Class_Centros_Custo();
                centros_custo.exclui(id_centro_custo);
                lista_centros_custo.setModel(centros_custo.carregaLista());
                txtNomeCentro.setText("");
                txtTipoCentroCusto.setText("");
                txtSaldoCentro.setText("");
            }
        }
        
    }//GEN-LAST:event_btnExcluirCentrosCustoActionPerformed

    private void btnSairCentrosCustoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairCentrosCustoActionPerformed
        
        Centros_Custo.dispose();
        
    }//GEN-LAST:event_btnSairCentrosCustoActionPerformed

    private void radioCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCaixaActionPerformed
        
        radioContaBancaria.setSelected(false);
        
    }//GEN-LAST:event_radioCaixaActionPerformed

    private void radioContaBancariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioContaBancariaActionPerformed
        
        radioCaixa.setSelected(false);
        
    }//GEN-LAST:event_radioContaBancariaActionPerformed

    private void btnConfigurarCentrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfigurarCentrosActionPerformed
        
        Class_Centros_Custo centros = new Class_Centros_Custo();
        lista_caixas.setModel(centros.refreshCaixas());
        comboUsuario.removeAllItems();
        comboUsuario.addItem("<Selecione>");
        Class_Usuarios usuarios = new Class_Usuarios();
        usuarios.carregaUsuariosNormaisComboBox(comboUsuario);
        comboUsuario.setSelectedIndex(0);
        lblCaixaSelecionado.setVisible(false);
        Configurar_Responsaveis_Caixa.setBounds(0, 0, 660, 490);
        Configurar_Responsaveis_Caixa.setLocationRelativeTo(null);
        Configurar_Responsaveis_Caixa.setVisible(true);
        
    }//GEN-LAST:event_btnConfigurarCentrosActionPerformed

    private void btnSairConfiguracaoResponsaveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairConfiguracaoResponsaveisActionPerformed
        
        Configurar_Responsaveis_Caixa.dispose();
        
    }//GEN-LAST:event_btnSairConfiguracaoResponsaveisActionPerformed

    private void lista_caixasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lista_caixasValueChanged
        
        Object caixa1 = lista_caixas.getSelectedValue();
        if (caixa1 == null) {
            lista_caixas.setSelectedIndex(0);
        }
        lblCaixaSelecionado.setVisible(true);
        String nome_caixa = lista_caixas.getSelectedValue().toString();
        lblCaixaSelecionado.setText(nome_caixa);
        Class_Caixa caixa = new Class_Caixa();
        lista_responsaveis.setModel(caixa.carregaResponsaveisCaixa(nome_caixa));
        
    }//GEN-LAST:event_lista_caixasValueChanged

    private void btnAdicionarResponsavelCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarResponsavelCaixaActionPerformed
        
        if (lista_caixas.getSelectedValue() == null) {
            JOptionPane.showMessageDialog(null, "Selecione o caixa desejado para adicionar os responsáveis!", "Atenção", JOptionPane.WARNING_MESSAGE);
        } else {
            if (comboUsuario.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(null, "Selecione o usuário para adicionar aos responsáveis!", "Atenção", JOptionPane.WARNING_MESSAGE);
            } else {
                ListModel lista = lista_responsaveis.getModel();
                String responsavel = comboUsuario.getSelectedItem().toString();
                boolean flag = false;
                for (int i = 0; i < lista.getSize(); i++) {
                    if (responsavel.equals(lista.getElementAt(i).toString())) {
                        flag = true;
                    }
                }
                if (flag == true) {
                    JOptionPane.showMessageDialog(null, "Este usuário já é responsável por este caixa!\nNão é preciso definí-lo novamente!", "Atenção", JOptionPane.WARNING_MESSAGE);
                } else {
                    Class_Usuarios usuarios = new Class_Usuarios();
                    int id_usuario = usuarios.getIdUsuario(responsavel);
                    Class_Centros_Custo centros = new Class_Centros_Custo();
                    int id_centro_custo = centros.retornaIdCentroCusto(lista_caixas.getSelectedValue().toString());
                    Class_Caixa caixa = new Class_Caixa();
                    caixa.adicionaResponsavelCaixa(id_centro_custo, id_usuario);
                    lista_responsaveis.setModel(caixa.carregaResponsaveisCaixa(lista_caixas.getSelectedValue().toString()));
                }
            }
        }
        
    }//GEN-LAST:event_btnAdicionarResponsavelCaixaActionPerformed

    private void btnRetirarResponsavelCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarResponsavelCaixaActionPerformed
        
        Object responsavel = lista_responsaveis.getSelectedValue();
        if (responsavel == null) {
            JOptionPane.showMessageDialog(null, "Selecione o responsável na lista abaixo para retirar!", "Atenção", JOptionPane.WARNING_MESSAGE);
        } else {
            Class_Usuarios usuarios = new Class_Usuarios();
            int id_usuario = usuarios.getIdUsuario(responsavel.toString());
            Class_Centros_Custo centros = new Class_Centros_Custo();
            int id_centro_custo = centros.retornaIdCentroCusto(lista_caixas.getSelectedValue().toString());
            Class_Caixa caixa = new Class_Caixa();
            caixa.retiraResponsavelCaixa(id_centro_custo, id_usuario);
            lista_responsaveis.setModel(caixa.carregaResponsaveisCaixa(lista_caixas.getSelectedValue().toString()));
        }
        
    }//GEN-LAST:event_btnRetirarResponsavelCaixaActionPerformed

    private void btnSairPainelFinanceiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairPainelFinanceiroActionPerformed
        
        Class_Verifica_Menu_Aberto verifica = new Class_Verifica_Menu_Aberto();
        int index = verifica.verificaMenuAberto(painel_principal, "Sistema financeiro   ");
        if (index >= 0) {
            painel_principal.remove(index);
        }
        
    }//GEN-LAST:event_btnSairPainelFinanceiroActionPerformed

    private void btnLancamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLancamentosActionPerformed

        carregaLancamentos();
        
        Lancamentos.setBounds(0, 0, 1010, 600);
        Lancamentos.setLocationRelativeTo(null);
        Lancamentos.setVisible(true);
        
    }//GEN-LAST:event_btnLancamentosActionPerformed

    private void btnPesquisarLancamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarLancamentoActionPerformed
        
        carregaLancamentos();
        
    }//GEN-LAST:event_btnPesquisarLancamentoActionPerformed

    private void btmLiquidarLancamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmLiquidarLancamentosActionPerformed
        
        int linha = tabelaLancamentos.getSelectedRow();
        if (linha == -1) {
            JOptionPane.showMessageDialog(null, "Selecione um lançamento na tabela para liquidar!", "Atenção", JOptionPane.WARNING_MESSAGE);
        } else {
            DefaultTableModel modelo = (DefaultTableModel) tabelaLancamentos.getModel();
            String liquidado = modelo.getValueAt(linha, 5).toString();
            if (liquidado.equals("Sim")) {
                JOptionPane.showMessageDialog(null, "Este lançamento já está liquidado!", "Atenção", JOptionPane.WARNING_MESSAGE);
            } else {
                if (JOptionPane.showConfirmDialog(null, "Deseja realmente liquidar este lançamento?", "Atenção", JOptionPane.YES_NO_OPTION) == 0) {
                    String tipo = modelo.getValueAt(linha, 6).toString();
                    int id = Integer.valueOf(modelo.getValueAt(linha, 7).toString());
                    if (tipo.equals("Receita")) {
                        Class_Receitas receitas = new Class_Receitas();
                        receitas.liquidarReceita(id);
                    } else {
                        Class_Despesas despesas = new Class_Despesas();
                        despesas.liquidarDespesa(id);
                    }
                    JOptionPane.showMessageDialog(null, "Lançamento liquidado com sucesso!", "Atenção", JOptionPane.INFORMATION_MESSAGE);

                    carregaLancamentos();
                }
            }
        }
        
    }//GEN-LAST:event_btmLiquidarLancamentosActionPerformed

    private void btnDesliquidarLancamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesliquidarLancamentosActionPerformed
        
        int linha = tabelaLancamentos.getSelectedRow();
        if (linha == -1) {
            JOptionPane.showMessageDialog(null, "Selecione um lançamento na tabela para desliquidar!", "Atenção", JOptionPane.WARNING_MESSAGE);
        } else {
            DefaultTableModel modelo = (DefaultTableModel) tabelaLancamentos.getModel();
            String liquidado = modelo.getValueAt(linha, 5).toString();
            if (liquidado.equals("Não")) {
                JOptionPane.showMessageDialog(null, "Este lançamento não está liquidado!", "Atenção", JOptionPane.WARNING_MESSAGE);
            } else {
                if (JOptionPane.showConfirmDialog(null, "Deseja realmente desliquidar este lançamento?", "Atenção", JOptionPane.YES_NO_OPTION) == 0) {
                    String tipo = modelo.getValueAt(linha, 6).toString();
                    int id = Integer.valueOf(modelo.getValueAt(linha, 7).toString());
                    if (tipo.equals("Receita")) {
                        Class_Receitas receitas = new Class_Receitas();
                        receitas.desliquidarReceita(id);
                    } else {
                        Class_Despesas despesas = new Class_Despesas();
                        despesas.desliquidarDespesa(id);
                    }
                    JOptionPane.showMessageDialog(null, "Lançamento desliquidado com sucesso!", "Atenção", JOptionPane.INFORMATION_MESSAGE);

                    carregaLancamentos();
                }
            }
        }
        
    }//GEN-LAST:event_btnDesliquidarLancamentosActionPerformed

    private void btnNovoLancamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoLancamentosActionPerformed
        
        limpaCamposNovoLancamento();
        Agendar_Lancamento.setBounds(0, 0, 670, 390);
        Agendar_Lancamento.setLocationRelativeTo(null);
        Agendar_Lancamento.setVisible(true);
        
    }//GEN-LAST:event_btnNovoLancamentosActionPerformed

    private void comboTipoNovoLancamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoNovoLancamentoActionPerformed

        if (comboTipoNovoLancamento.getSelectedItem().toString().equals("Receita")) {
            Class_Formas_Pagto formas = new Class_Formas_Pagto();
            formas.carregaFormasPagamento(comboFormaNovoLancamento);
            comboFormaNovoLancamento.setEnabled(true);
        } else {
            comboFormaNovoLancamento.removeAllItems();
            comboFormaNovoLancamento.addItem("Dinheiro");
            comboFormaNovoLancamento.setEnabled(false);
        }

    }//GEN-LAST:event_comboTipoNovoLancamentoActionPerformed

    private void txtValorNovoLancamentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorNovoLancamentoKeyTyped

        Class_Consumir_Letras cons = new Class_Consumir_Letras();
        cons.consome("1234567890,.", evt);
        
    }//GEN-LAST:event_txtValorNovoLancamentoKeyTyped

    private void btnSalvarNovoLancamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarNovoLancamentoActionPerformed
/*
        if (txtDescricaoNovoLancamento.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Digite a descrição do lançamento!", "Atenção", JOptionPane.WARNING_MESSAGE);
            txtDescricaoNovoLancamento.grabFocus();
        } else if (txtValorNovoLancamento.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Digite o valor do lançamento!", "Atenção", JOptionPane.WARNING_MESSAGE);
            txtValorNovoLancamento.grabFocus();
        } else {
            String forma = comboFormaNovoLancamento.getSelectedItem().toString();
            //Adicionando a movimentação
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
            String data = sdf.format(new Date());

            Class_Conta_Bancaria conta = new Class_Conta_Bancaria();
            conta.registraMovimentacaoContaBancaria(id_centro_custo, txtDescricaoNovoLancamento.getText(), forma, 1,
                txtValorNovoLancamento.getText(), comboTipoNovoLancamento.getSelectedItem().toString(), id_usuario,
                data);
            conta.carregaMovimentacoesContaBancaria((DefaultTableModel) tabelaMovimentacoesContaBancaria.getModel(),
                id_centro_custo, dataPesquisa1.getDate(), dataPesquisa2.getDate());

            int id_movimentacao_conta_bancaria = conta.getIdUltimaMovimentacaoContaBancaria();
            if (comboTipoNovoLancamento.getSelectedItem().toString().equals("Receita")) {
                Class_Receitas receitas = new Class_Receitas();
                receitas.cadastraReceita(txtDescricaoNovoLancamento.getText(), 0, "", "Entrada na conta bancária", forma,
                    txtValorNovoLancamento.getText(), "0", "0", 1, 0, id_movimentacao_conta_bancaria, data, data);
            } else if (comboTipoNovoLancamento.getSelectedItem().equals("Despesa")) {
                Class_Despesas despesas = new Class_Despesas();
                despesas.cadastraDespesa(0, txtDescricaoNovoLancamento.getText(), nome_usuario, "", 1, data, data, forma,
                    txtValorNovoLancamento.getText(), "0", "0", 0, 1, "Saída na conta bancária", id_usuario, 0,
                    id_movimentacao_conta_bancaria);
            }

            Class_Centros_Custo centros = new Class_Centros_Custo();
            centros.alteraSaldoCentroCusto(comboTipoNovoLancamento.getSelectedItem().toString(), "0,00",
                txtValorNovoLancamento.getText(), id_centro_custo);

            JOptionPane.showMessageDialog(null, "Lançamento realizado com sucesso!", "Atenção", JOptionPane.INFORMATION_MESSAGE);
            Novo_Lancamento.dispose();
        }*/
    }//GEN-LAST:event_btnSalvarNovoLancamentoActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed

        limpaCamposNovoLancamento();
        
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnSairNovoLancamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairNovoLancamentoActionPerformed

        Agendar_Lancamento.dispose();
    }//GEN-LAST:event_btnSairNovoLancamentoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Agendar_Lancamento;
    private javax.swing.JDialog Alterar_Centro_Custo;
    private javax.swing.JDialog Centros_Custo;
    private javax.swing.JDialog Configurar_Responsaveis_Caixa;
    private javax.swing.JDialog Lancamentos;
    private javax.swing.JDialog Novo_Centro_Custo;
    private javax.swing.JButton btmLiquidarLancamentos;
    private javax.swing.JButton btnAdicionarResponsavelCaixa;
    private javax.swing.JButton btnAlterarCentrosCusto;
    private javax.swing.JButton btnAlterarLancamentos;
    private javax.swing.JButton btnCentrosCusto;
    private javax.swing.JButton btnConfigurarCentros;
    private javax.swing.JButton btnDesliquidarLancamentos;
    private javax.swing.JButton btnExcluirCentrosCusto;
    private javax.swing.JButton btnExcluirLancamentos;
    private javax.swing.JButton btnLancamentos;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnLimparDadosCentroCusto;
    private javax.swing.JButton btnNovoCentroCusto;
    private javax.swing.JButton btnNovoLancamentos;
    private javax.swing.JButton btnPesquisarLancamento;
    private javax.swing.JButton btnRetirarResponsavelCaixa;
    private javax.swing.JButton btnSairCadastroCentroCusto;
    private javax.swing.JButton btnSairCadastroCentroCusto2;
    private javax.swing.JButton btnSairCentrosCusto;
    private javax.swing.JButton btnSairConfiguracaoResponsaveis;
    private javax.swing.JButton btnSairLancamentos;
    private javax.swing.JButton btnSairNovoLancamento;
    private javax.swing.JButton btnSairPainelFinanceiro;
    private javax.swing.JButton btnSalvarCentroCusto;
    private javax.swing.JButton btnSalvarCentroCusto2;
    private javax.swing.JButton btnSalvarNovoLancamento;
    private javax.swing.JComboBox comboFormaNovoLancamento;
    private javax.swing.JComboBox comboParcelasNovoLancamento;
    private javax.swing.JComboBox comboPesquisaLancamentos;
    private javax.swing.JComboBox comboSituacaoLancamentos;
    private javax.swing.JComboBox comboTipoNovoLancamento;
    private javax.swing.JComboBox comboUsuario;
    private com.toedter.calendar.JDateChooser dataPesquisa1Lancamentos;
    private com.toedter.calendar.JDateChooser dataPesquisa2Lancamentos;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblCaixaSelecionado;
    private javax.swing.JLabel lblTipoCentroCusto;
    private javax.swing.JList lista_caixas;
    private javax.swing.JList lista_centros_custo;
    private javax.swing.JList lista_responsaveis;
    private javax.swing.JRadioButton radioCaixa;
    private javax.swing.JRadioButton radioContaBancaria;
    private javax.swing.JTable tabelaLancamentos;
    private javax.swing.JTextField txtDescricaoNovoLancamento;
    private javax.swing.JTextField txtNomeCentro;
    private javax.swing.JTextField txtNomeCentro1;
    private javax.swing.JTextField txtNomeCentro2;
    private javax.swing.JTextField txtSaldoCentro;
    private javax.swing.JTextField txtTipoCentroCusto;
    private javax.swing.JTextField txtValorNovoLancamento;
    // End of variables declaration//GEN-END:variables
}
